### ISSUE TITLE
Failure in refreshing existing auth token make main login to appear after 20 seconds waiting

### ISSUE THREAD

**Issue by photonn** [epam/ai-dial-chat#1075]
### EPAM AI DIAL chat version

0.6.12

### How to reproduce

- go to main url and login when login appears
- close the browser without logout
- After auth token expires, open the browser and go to main page again
- You will see that it takes 20 seconds to appear, and an error is logged in in chat logs

[09:28:57.641] ERROR (18): Error when refreshing token: Waiting more than 20 seconds for refreshing token. Sub: 1a7tUPQfh856EEoC8sAy_qN-7TZnMV8IKqyLlusOuFw [trace_id=, span_id=]

    err: {
      "type": "Error",
      "message": "Waiting more than 20 seconds for refreshing token",
      "stack":
          Error: Waiting more than 20 seconds for refreshing token
              at refreshAccessToken (/app/.next/server/chunks/902.js:5:21905)
              at async Object.session (/app/node_modules/next-auth/core/routes/session.js:47:21)
              at async AuthHandler (/app/node_modules/next-auth/core/index.js:165:27)
              at async getServerSession (/app/node_modules/next-auth/next/index.js:159:19)
              at async getServerSideProps (/app/.next/server/pages/index.js:2:243630)
    }

### Actual result

main login page take 20 seconds to appear until a refresing of the current auth token expires

### Expected result

login page appears in a reasonable ammount of time.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by photonn** [comment]
I also see this error in the logs:

[12:43:36.918] ERROR (18): Error when refreshing token: invalid_grant (AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: fedf98a4-109d-47a0-bb37-598941561700 Correlation ID: d4b198cf-8376-4b76-a9ac-fd4ef016a857 Timestamp: 2024-03-18 12:43:36Z). Sub: ****** [trace_id=, span_id=]
    err: {
      "type": "OPError",
      "message": "invalid_grant (AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: fedf98a4-109d-47a0-bb37-598941561700 Correlation ID: d4b198cf-8376-4b76-a9ac-fd4ef016a857 Timestamp: 2024-03-18 12:43:36Z)",
      "stack":
          OPError: invalid_grant (AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: fedf98a4-109d-47a0-bb37-598941561700 Correlation ID: d4b198cf-8376-4b76-a9ac-fd4ef016a857 Timestamp: 2024-03-18 12:43:36Z)
              at processResponse (/app/node_modules/openid-client/lib/helpers/process_response.js:38:13)
              at Client.grant (/app/node_modules/openid-client/lib/client.js:1354:22)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Client.refresh (/app/node_modules/openid-client/lib/client.js:1098:22)
              at async refreshAccessToken (/app/.next/server/chunks/902.js:5:21970)
              at async Object.session (/app/node_modules/next-auth/core/routes/session.js:47:21)
              at async AuthHandler (/app/node_modules/next-auth/core/index.js:165:27)
              at async getServerSession (/app/node_modules/next-auth/next/index.js:159:19)
              at async getServerSideProps (/app/.next/server/pages/index.js:2:243630)
      "error": "invalid_grant",
      "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: fedf98a4-109d-47a0-bb37-598941561700 Correlation ID: d4b198cf-8376-4b76-a9ac-fd4ef016a857 Timestamp: 2024-03-18 12:43:36Z",
      "error_uri": "https://login.microsoftonline.com/error?code=9002313",
      "name": "OPError"
    }

**Comment by IlyaBondar** [comment]
Partial was fixed by descresing the timeout in https://github.com/epam/ai-dial-chat/pull/1114
Will continue investigation in #1116
