### ISSUE TITLE
Investigate and handle error with refresh token

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1116]
### EPAM AI DIAL chat version

0.6.12

### Description

Related to #1075 
Partial was fixed by descresing the timeout in #1114

### How to reproduce
- go to main url and login when login appears
- close the browser without logout
- After auth token expires, open the browser and go to main page again
- You will see that it takes 20 seconds to appear, and an error is logged in in chat logs

> [09:28:57.641] ERROR (18): Error when refreshing token: Waiting more than 20 seconds for refreshing token. Sub: 1a7tUPQfh856EEoC8sAy_qN-7TZnMV8IKqyLlusOuFw [trace_id=, span_id=]

```javascript
err: {
  "type": "Error",
  "message": "Waiting more than 20 seconds for refreshing token",
  "stack":
      Error: Waiting more than 20 seconds for refreshing token
          at refreshAccessToken (/app/.next/server/chunks/902.js:5:21905)
          at async Object.session (/app/node_modules/next-auth/core/routes/session.js:47:21)
          at async AuthHandler (/app/node_modules/next-auth/core/index.js:165:27)
          at async getServerSession (/app/node_modules/next-auth/next/index.js:159:19)
          at async getServerSideProps (/app/.next/server/pages/index.js:2:243630)
}
```

### Actual result

main login page take 20 seconds to appear until a refresing of the current auth token expires

### Expected result

login page appears in a reasonable ammount of time.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YuriiDavydiak** [comment]
tested on dev
Version 0.46.0-dev.114
The issue looks like an obsolete one or has been fixed in another scope
