### ISSUE TITLE
Error in console appear if to open the server (SyntaxError: "undefined" is not valid JSON at DataService.getCustomLogo)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1188]
### EPAM AI DIAL chat version

0.9.0

### What happened?

Open console and open DIAL on staging env -> error in console -> **regression bug**

_app-472b05a8bd193810.js:33 SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at BrowserStorage.getData (_app-472b05a8bd193810.js:33:304272)
    at DataService.getCustomLogo (_app-472b05a8bd193810.js:33:124193)
    at _app-472b05a8bd193810.js:33:224387
    at _app-472b05a8bd193810.js:41:22162
    at OperatorSubscriber.en._next (_app-472b05a8bd193810.js:41:20442)
    at Subscriber.next (_app-472b05a8bd193810.js:41:10022)
    at _app-472b05a8bd193810.js:33:113267
    at OperatorSubscriber.en._next (_app-472b05a8bd193810.js:41:20442)
    at Subscriber.next (_app-472b05a8bd193810.js:41:10022)
    
   

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. 
If there is still an error in console, please remove in local storage customLogo = undentified or just reset logo thu UI (DIAL settings under user name menu).
