### ISSUE TITLE
Invalid JWT error for Google Cloud provider

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2003]
### EPAM AI DIAL chat version

0.16.0

### What happened?

Need to fix `Invalid JWT` error for Google Cloud provider during `decodeJwt` executing
```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error Invalid JWT {
  message: 'Invalid JWT',
  stack: 'JWTInvalid: Invalid JWT\n' +
    '    at decodeJwt (file:///app/node_modules/jose/dist/node/esm/util/decode_jwt.js:12:15)\n' +
    '    at Object.jwt (/app/.next/server/pages/api/auth/[...nextauth].js:1:4306)\n' +
    '    at Object.callback (/app/node_modules/next-auth/core/routes/callback.js:135:41)\n' +
    '    at async AuthHandler (/app/node_modules/next-auth/core/index.js:208:28)\n' +
    '    at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)\n' +
    '    at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:108:14)\n' +
    '    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)\n' +
    '    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)\n' +
    '    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:554:9)\n' +
    '    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:266:37)',
  name: 'JWTInvalid'
}
```

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by tataranovich** [comment]
@IlyaBondar I tried chat 0.16.4 and now Google Cloud identity provider is working.

**Comment by YauheniyaH** [comment]
tested by entering stg 0.17.0 with google account - working
