### ISSUE TITLE
Use `model.reference` instead of `model.id` everywhere in `conversation.model.id` (Error 412)

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2080]
### EPAM AI DIAL chat version

0.16.0

### What happened?

Error:
```
POST https://dev-dial-chat.staging.deltixhub.io/api/conversations/7vRZWEFg52Y1tQ…%2520with%2520history%2520(Claude)%255F%255F0.0.1__New%20conversation%2052 412 (Precondition Failed)
_app-d6202dcaef71f694.js:41 

POST https://dev-dial-chat.staging.deltixhub.io/api/conversations/7vRZWEFg52Y1tQ…%2520with%2520history%2520(Claude)%255F%255F0.0.1__New%20conversation%2052 412 (Precondition Failed)
_app-d6202dcaef71f694.js:33 
New conversation wasn't created:  Error: Precondition Failed
    at _app-d6202dcaef71f694.js:33:368191
    at e.i [as _subscribe] (_app-d6202dcaef71f694.js:41:18008)
    at e._trySubscribe (_app-d6202dcaef71f694.js:41:7569)
    at _app-d6202dcaef71f694.js:41:7492
    at i (_app-d6202dcaef71f694.js:41:23068)
    at e.subscribe (_app-d6202dcaef71f694.js:41:7412)
    at _app-d6202dcaef71f694.js:41:21259
    at t._next (_app-d6202dcaef71f694.js:41:18341)
    at t.next (_app-d6202dcaef71f694.js:41:8972)
    at _app-d6202dcaef71f694.js:41:16517
```
must be `reference`(guid) instead of `%2520with%2520history%2520(Claude)%255F%255F0.0.1` (`id`)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env. No we use custom application 'reference' in conversation Id
![image](https://github.com/user-attachments/assets/113e9b68-80fa-4006-a84f-e31f349a7508)
![image](https://github.com/user-attachments/assets/73ac5e1c-fda8-4f69-afd8-651356c23154)
