### ISSUE TITLE
Cannot run docker image 0.4.3

### ISSUE THREAD

**Issue by AdamKrzysiek** [epam/ai-dial-chat#658]
Image: epam/ai-dial-chat
Tag: 0.4.3

Dockerhub image of ai-dial-chat execution fails with following log:

[+] Building 0.0s (0/0)                                                                                                                                                                          docker:colima
[+] Building 0.0s (0/0)                                                                                                                                                                          docker:colima

> dial-chat@0.4.3 start
> next start

 ⚠ Invalid next.config.js options detected: 
 ⚠     The value at .basePath must be a string but it was an object.
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000

 ✓ Ready in 3.4s
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.4.0
npm notice Run npm install -g npm@10.4.0 to update!
npm notice 
npm ERR! path /app
npm ERR! command failed
npm ERR! signal SIGKILL
npm ERR! command sh -c next start

npm ERR! A complete log of this run can be found in: /home/nextjs/.npm/_logs/2024-02-08T14_49_16_970Z-debug-0.log

**### Log from dev run:**
/app $ npm run start

> dial-chat@0.4.3 start
> next start

 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
 ⚠ Invalid next.config.js options detected: 
 ⚠     The value at .basePath must be a string but it was an object.
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000

 ✓ Ready in 3.3s

Killed
/app $ 
/app $ npm run dev

> dial-chat@0.4.3 dev
> next dev

 ⚠ Invalid next.config.js options detected: 
 ⚠     The value at .basePath must be a string but it was an object.
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (/app/node_modules/next/dist/lib/find-pages-dir.js:42:15)
    at initialize (/app/node_modules/next/dist/server/lib/router-server.js:67:69)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:219:36)

**Comment by mikitabut** [comment]
Hello @AdamKrzysiek 
Could you please provide the logs from npm on your first fail?

**Comment by AdamKrzysiek** [comment]
@mikitabut 
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.2.4
2 info using node@v20.11.0
3 timing npm:load:whichnode Completed in 13ms
4 timing config:load:defaults Completed in 24ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 7ms
6 timing config:load:builtin Completed in 10ms
7 timing config:load:cli Completed in 20ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/app/.npmrc Completed in 0ms
10 timing config:load:project Completed in 18ms
11 timing config:load:file:/home/nextjs/.npmrc Completed in 1ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 2ms
15 timing config:load:setEnvs Completed in 6ms
16 timing config:load Completed in 99ms
17 timing npm:load:configload Completed in 99ms
18 timing config:load:flatten Completed in 41ms
19 timing npm:load:mkdirpcache Completed in 11ms
20 timing npm:load:mkdirplogs Completed in 4ms
21 verbose title npm start
22 verbose argv "start"
23 timing npm:load:setTitle Completed in 16ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:/home/nextjs/.npm/_logs/2024-02-08T21_47_04_803Z-
26 verbose logfile /home/nextjs/.npm/_logs/2024-02-08T21_47_04_803Z-debug-0.log
27 timing npm:load:logFile Completed in 110ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 467ms
31 silly logfile done cleaning log files
32 timing command:run-script Completed in 30525ms
33 timing command:start Completed in 30606ms
34 verbose stack Error: command failed
34 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
34 verbose stack     at ChildProcess.emit (node:events:518:28)
34 verbose stack     at maybeClose (node:internal/child_process:1105:16)
34 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
35 verbose pkgid dial-chat@0.4.3
36 verbose cwd /app
37 verbose Linux 6.1.55-0-virt
38 verbose node v20.11.0
39 verbose npm  v10.2.4
40 error path /app
41 error command failed
42 error signal SIGKILL
43 error command sh -c next start
44 verbose exit 1
45 timing npm Completed in 31516ms
46 verbose code 1
47 error A complete log of this run can be found in: /home/nextjs/.npm/_logs/2024-02-08T21_47_04_803Z-debug-0.log

**Comment by PolinaGurinovich97** [comment]
please, re-open if still actual
